agents:
  librarian:
    path: agents/librarian/main.py
    role: Fetches PDFs from public government portals
  librarian_scheduler:
    path: agents/librarian/scheduler.py
    role: Schedules periodic crawling of Kenya policy sources
  interpreter:
    path: agents/interpreter/main.py
    role: Extracts and structures content from PDFs
  summarizer:
    path: agents/summarizer/main.py
    role: Summarizes structured data using LLMs
  ethical_analyst:
    path: agents/ethical_analyst/main.py
    role: Integrates with cognitive_core for ethical reasoning
  communicator:
    path: agents/communicator/main.py
    role: Interfaces with human ethics partner via dashboard
    name: "Twilio"
    api_key: "agent1qfcx8z8a5muprru7gvq0mkg9rn7x07my02z4z87u4ctfk02jc0ygwppw9fk"
    type: "communications"
  orchestrator:
    path: agents/orchestrator/main.py
    role: Routes messages across the pipeline
    name: "Aethel"
    api_key: "sk_dfdb772ee76f4a519f2d81870831911bb99530554f754e36a29aad452bf729df"
    type: "orchestrator_sentinel"
  agent_registry:
    path: agents/agent_registry/main.py
    role: Registry and blockchain coordination
    name: "Agent Registry"
    agent_id: "agent1q28ryexcvl2hv55gatd4dur07tlzcweqxmyk6dahrn4va0sdqt2lk2zfywa"
    endpoint: "https://agentverse.ai/agents/details/agent1q28ryexcvl2hv55gatd4dur07tlzcweqxmyk6dahrn4va0sdqt2lk2zfywa/profile"
    type: "registry_blockchain"
  social_monitor:
    path: agents/social_monitor/main.py
    role: Polls RSS/social feeds and triggers crawls

registry:
  provider: asi-cloud
  project: EPPN
  environment: dev

agentverse:
  # AgentVerse integration token - prefer setting as environment variable
  # Do NOT commit real tokens to source control. Set AGENTVERSE_TOKEN in the
  # deployment environment or CI secrets and leave this as a placeholder.
  token_env: AGENTVERSE_TOKEN
  api_url: https://api.agentverse.ai

messaging:
  schemas: schemas/messages.py
  channels:
    - name: policy_pipeline
      agents: [orchestrator, librarian, librarian_scheduler, interpreter, summarizer, ethical_analyst, communicator, social_monitor]


